[project]
name = "daw_core"
version = "1.0.0"
description = "Core configuration and utilities for DAW"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.34.131",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

